paths:
  base_dir: /eos/uscms/store/user/lpcdihiggsboost/yucao/v7_analysis/Version_20260706_final_test1
  sample_base: individual_samples          
  model_base: SnT_like_model/epoch400     
  output_base: /eos/uscms/store/group/lpcdihiggsboost/nparekh/yuxiang_resample/two_fold_model_old

model:
  ext: BhF2E400          
  n_classes: 4
  fill_nan: -9
  batch_size: 65536
  num_layers: 5
  num_nodes: 1024
  act_fn: ELU
  dropout_prob: 0.25

class_names:              
  - is_nonRes_bkg
  - is_Res_bkg
  - is_ggHH_sig
  - is_VBFHH_sig

resample:
  signal_sample: GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00
  background_samples:
    - DDQCDGJET
    - GGJets
    - TTGG
  combo_name: mvaID_btag_dijetmass
  seed: 21

  presel_cuts:
    - column: lead_mvaID
      op: ">"
      value: -0.7
    - column: sublead_mvaID
      op: ">"
      value: -0.7
    - column: nonResReg_vbfpair_dijet_mass_DNNreg
      op: ">"
      value: 80
    - column: nonResReg_vbfpair_dijet_mass_DNNreg
      op: "<"
      value: 180

  hist_vars:
    - name: lead_mvaID
      bins: 100
    - name: sublead_mvaID
      bins: 100
    - name: nonResReg_vbfpair_dijet_mass_DNNreg
      bins: 100

  fixed_vars:
    value: 1.0
    columns:
      - nonResReg_vbfpair_lead_bjet_btag_WP_L
      - nonResReg_vbfpair_lead_bjet_btag_WP_M
      - nonResReg_vbfpair_lead_bjet_btag_WP_T
      - nonResReg_vbfpair_lead_bjet_btag_WP_XT
      - nonResReg_vbfpair_lead_bjet_btag_WP_XXT
      - nonResReg_vbfpair_sublead_bjet_btag_WP_L
      - nonResReg_vbfpair_sublead_bjet_btag_WP_M
      - nonResReg_vbfpair_sublead_bjet_btag_WP_T
      - nonResReg_vbfpair_sublead_bjet_btag_WP_XT
      - nonResReg_vbfpair_sublead_bjet_btag_WP_XXT

output_vars:
  - column: mass
    out_name: diphoton_mass
  - column: nonResReg_vbfpair_dijet_mass_DNNreg
    out_name: dijet_mass
  - column: nonResReg_vbfpair_HHbbggCandidate_mass
    out_name: HH_mass

cuts:
  no_cut: {}
  vbfhh_cat1:
    is_VBFHH_sig: {op: "<", value: 0.907}
  cat1:
    is_ggHH_sig:   {op: ">", value: 0.972}
    is_nonRes_bkg: {op: "<", value: 0.0002}
    is_Res_bkg:    {op: "<", value: 0.00396}
    is_VBFHH_sig:  {op: "<", value: 0.907}
  cat2:
    is_ggHH_sig:   {op: ">", value: 0.228}
    is_nonRes_bkg: {op: "<", value: 0.0002}
    is_Res_bkg:    {op: "<", value: 0.00994}
    is_VBFHH_sig:  {op: "<", value: 0.907}
  cat3:
    is_ggHH_sig:   {op: ">", value: 0.97016}
    is_nonRes_bkg: {op: "<", value: 0.00138}
    is_Res_bkg:    {op: "<", value: 0.02842}
    is_VBFHH_sig:  {op: "<", value: 0.907}

plot_vars:
  - name: diphoton_mass
    bins: 32
    range: [100, 180]
  - name: dijet_mass
    bins: 32
    range: [100, 180]
  - name: HH_mass
    bins: 45
    range: [100, 1000]